[2024-09-29T00:00:07.471+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-29T00:00:07.539+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: process_employees.merge_data scheduled__2024-09-28T00:00:00+00:00 [queued]>
[2024-09-29T00:00:07.557+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: process_employees.merge_data scheduled__2024-09-28T00:00:00+00:00 [queued]>
[2024-09-29T00:00:07.558+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-09-29T00:00:07.596+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): merge_data> on 2024-09-28 00:00:00+00:00
[2024-09-29T00:00:07.608+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'process_employees', 'merge_data', 'scheduled__2024-09-28T00:00:00+00:00', '--job-id', '212', '--raw', '--subdir', 'DAGS_FOLDER/etl_prueba.py', '--cfg-path', '/tmp/tmpsi3d1rwt']
[2024-09-29T00:00:07.611+0000] {standard_task_runner.py:91} INFO - Job 212: Subtask merge_data
[2024-09-29T00:00:07.617+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=475) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-29T00:00:07.618+0000] {standard_task_runner.py:63} INFO - Started process 476 to run task
[2024-09-29T00:00:07.690+0000] {task_command.py:426} INFO - Running <TaskInstance: process_employees.merge_data scheduled__2024-09-28T00:00:00+00:00 [running]> on host 5e909a8df6c4
[2024-09-29T00:00:07.850+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='process_employees' AIRFLOW_CTX_TASK_ID='merge_data' AIRFLOW_CTX_EXECUTION_DATE='2024-09-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-28T00:00:00+00:00'
[2024-09-29T00:00:07.852+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-29T00:00:07.865+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2024-09-29T00:00:07.995+0000] {python.py:237} INFO - Done. Returned value was: 0
[2024-09-29T00:00:07.997+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-29T00:00:08.073+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=process_employees, task_id=merge_data, run_id=scheduled__2024-09-28T00:00:00+00:00, execution_date=20240928T000000, start_date=20240929T000007, end_date=20240929T000008
[2024-09-29T00:00:08.126+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-09-29T00:00:08.165+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-29T00:00:08.171+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
