[2024-12-03T00:00:05.597+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-12-03T00:00:05.659+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: process_variables_financieras.get_data_var4 scheduled__2024-12-02T00:00:00+00:00 [queued]>
[2024-12-03T00:00:05.954+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: process_variables_financieras.get_data_var4 scheduled__2024-12-02T00:00:00+00:00 [queued]>
[2024-12-03T00:00:05.954+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-12-03T00:00:05.992+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): get_data_var4> on 2024-12-02 00:00:00+00:00
[2024-12-03T00:00:06.006+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=102181) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-12-03T00:00:06.008+0000] {standard_task_runner.py:63} INFO - Started process 102190 to run task
[2024-12-03T00:00:06.011+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'process_variables_financieras', 'get_data_var4', 'scheduled__2024-12-02T00:00:00+00:00', '--job-id', '402', '--raw', '--subdir', 'DAGS_FOLDER/etl_prueba.py', '--cfg-path', '/tmp/tmpae0kk9lj']
[2024-12-03T00:00:06.014+0000] {standard_task_runner.py:91} INFO - Job 402: Subtask get_data_var4
[2024-12-03T00:00:06.105+0000] {task_command.py:426} INFO - Running <TaskInstance: process_variables_financieras.get_data_var4 scheduled__2024-12-02T00:00:00+00:00 [running]> on host 5e909a8df6c4
[2024-12-03T00:00:06.382+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='process_variables_financieras' AIRFLOW_CTX_TASK_ID='get_data_var4' AIRFLOW_CTX_EXECUTION_DATE='2024-12-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-02T00:00:00+00:00'
[2024-12-03T00:00:06.385+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-12-03T00:00:06.679+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/urllib3/connectionpool.py:1103 InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.bcra.gob.ar'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
[2024-12-03T00:00:06.758+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-12-03T00:00:06.760+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-12-03T00:00:06.779+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=process_variables_financieras, task_id=get_data_var4, run_id=scheduled__2024-12-02T00:00:00+00:00, execution_date=20241202T000000, start_date=20241203T000005, end_date=20241203T000006
[2024-12-03T00:00:06.832+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-12-03T00:00:06.892+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-12-03T00:00:06.900+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
