[2024-12-03T00:00:08.677+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-12-03T00:00:08.744+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: process_variables_financieras.consumo_stg_var1 scheduled__2024-12-02T00:00:00+00:00 [queued]>
[2024-12-03T00:00:09.038+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: process_variables_financieras.consumo_stg_var1 scheduled__2024-12-02T00:00:00+00:00 [queued]>
[2024-12-03T00:00:09.039+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-12-03T00:00:09.079+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): consumo_stg_var1> on 2024-12-02 00:00:00+00:00
[2024-12-03T00:00:09.096+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=102192) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-12-03T00:00:09.098+0000] {standard_task_runner.py:63} INFO - Started process 102196 to run task
[2024-12-03T00:00:09.105+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'process_variables_financieras', 'consumo_stg_var1', 'scheduled__2024-12-02T00:00:00+00:00', '--job-id', '404', '--raw', '--subdir', 'DAGS_FOLDER/etl_prueba.py', '--cfg-path', '/tmp/tmpwi06qdk3']
[2024-12-03T00:00:09.108+0000] {standard_task_runner.py:91} INFO - Job 404: Subtask consumo_stg_var1
[2024-12-03T00:00:09.207+0000] {task_command.py:426} INFO - Running <TaskInstance: process_variables_financieras.consumo_stg_var1 scheduled__2024-12-02T00:00:00+00:00 [running]> on host 5e909a8df6c4
[2024-12-03T00:00:09.447+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='process_variables_financieras' AIRFLOW_CTX_TASK_ID='consumo_stg_var1' AIRFLOW_CTX_EXECUTION_DATE='2024-12-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-02T00:00:00+00:00'
[2024-12-03T00:00:09.452+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-12-03T00:00:09.466+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2024-12-03T00:00:09.513+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-12-03T00:00:09.514+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-12-03T00:00:09.530+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=process_variables_financieras, task_id=consumo_stg_var1, run_id=scheduled__2024-12-02T00:00:00+00:00, execution_date=20241202T000000, start_date=20241203T000008, end_date=20241203T000009
[2024-12-03T00:00:09.648+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-12-03T00:00:09.682+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-12-03T00:00:09.704+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
