[2024-10-04T20:56:15.195+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-04T20:56:15.412+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: process_employees.get_data manual__2024-10-04T20:56:01.030923+00:00 [queued]>
[2024-10-04T20:56:15.505+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: process_employees.get_data manual__2024-10-04T20:56:01.030923+00:00 [queued]>
[2024-10-04T20:56:15.506+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-04T20:56:16.208+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): get_data> on 2024-10-04 20:56:01.030923+00:00
[2024-10-04T20:56:16.263+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'process_employees', 'get_data', 'manual__2024-10-04T20:56:01.030923+00:00', '--job-id', '277', '--raw', '--subdir', 'DAGS_FOLDER/etl_prueba.py', '--cfg-path', '/tmp/tmp3li8tyr_']
[2024-10-04T20:56:16.288+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=515) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-10-04T20:56:16.300+0000] {standard_task_runner.py:63} INFO - Started process 517 to run task
[2024-10-04T20:56:16.284+0000] {standard_task_runner.py:91} INFO - Job 277: Subtask get_data
[2024-10-04T20:56:16.537+0000] {task_command.py:426} INFO - Running <TaskInstance: process_employees.get_data manual__2024-10-04T20:56:01.030923+00:00 [running]> on host 5e909a8df6c4
[2024-10-04T20:56:17.174+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='process_employees' AIRFLOW_CTX_TASK_ID='get_data' AIRFLOW_CTX_EXECUTION_DATE='2024-10-04T20:56:01.030923+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-04T20:56:01.030923+00:00'
[2024-10-04T20:56:17.194+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-04T20:56:17.550+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/urllib3/connectionpool.py:1103 InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.bcra.gob.ar'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
[2024-10-04T20:56:17.626+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-10-04T20:56:17.633+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-04T20:56:17.662+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=process_employees, task_id=get_data, run_id=manual__2024-10-04T20:56:01.030923+00:00, execution_date=20241004T205601, start_date=20241004T205615, end_date=20241004T205617
[2024-10-04T20:56:17.784+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-10-04T20:56:17.875+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-04T20:56:17.886+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
