[2024-12-02T00:00:05.367+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-12-02T00:00:05.441+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: process_variables_financieras.get_data_var1 scheduled__2024-12-01T00:00:00+00:00 [queued]>
[2024-12-02T00:00:05.906+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: process_variables_financieras.get_data_var1 scheduled__2024-12-01T00:00:00+00:00 [queued]>
[2024-12-02T00:00:05.910+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-12-02T00:00:05.964+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): get_data_var1> on 2024-12-01 00:00:00+00:00
[2024-12-02T00:00:06.004+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=52010) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-12-02T00:00:05.990+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'process_variables_financieras', 'get_data_var1', 'scheduled__2024-12-01T00:00:00+00:00', '--job-id', '394', '--raw', '--subdir', 'DAGS_FOLDER/etl_prueba.py', '--cfg-path', '/tmp/tmp_m15r6gv']
[2024-12-02T00:00:06.010+0000] {standard_task_runner.py:91} INFO - Job 394: Subtask get_data_var1
[2024-12-02T00:00:06.006+0000] {standard_task_runner.py:63} INFO - Started process 52014 to run task
[2024-12-02T00:00:06.154+0000] {task_command.py:426} INFO - Running <TaskInstance: process_variables_financieras.get_data_var1 scheduled__2024-12-01T00:00:00+00:00 [running]> on host 5e909a8df6c4
[2024-12-02T00:00:06.436+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='process_variables_financieras' AIRFLOW_CTX_TASK_ID='get_data_var1' AIRFLOW_CTX_EXECUTION_DATE='2024-12-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-01T00:00:00+00:00'
[2024-12-02T00:00:06.438+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-12-02T00:00:06.747+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/urllib3/connectionpool.py:1103 InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.bcra.gob.ar'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
[2024-12-02T00:00:06.844+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-12-02T00:00:06.846+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-12-02T00:00:06.888+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=process_variables_financieras, task_id=get_data_var1, run_id=scheduled__2024-12-01T00:00:00+00:00, execution_date=20241201T000000, start_date=20241202T000005, end_date=20241202T000006
[2024-12-02T00:00:06.970+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-12-02T00:00:07.053+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-12-02T00:00:07.059+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
